version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "greatislander"
    reviewers:
      - "greatislander"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "greatislander"
    reviewers:
      - "greatislander"
